# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-25 09:04
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multimeter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniversalJsonContainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.PositiveIntegerField(default=0)),
                ('content_type', models.CharField(default=b'data', max_length=64)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.DeleteModel(
            name='Greeting',
        ),
    ]
